# Redirect
<VirtualHost *:80>
    ServerName rigoroushuman.com
    ServerAlias www.rigoroushuman.com
    ServerAlias 34.178.185.8

    RewriteEngine On

    # Force redirect EVERYTHING to HTTPS domain
    RewriteRule ^ https://rigoroushuman.com%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
	ServerName rigoroushuman.com
	ServerAlias www.rigoroushuman.com
	ServerAlias 34.178.185.8

	ProxyPreserveHost On

	ProxyPass / http://127.0.0.1:3000/ retry=1 timeout=5 acquire=3000 keepalive=On
	ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>